### ISSUE TITLE
Fix issue with random exceptions while Hashing

### ISSUE THREAD

**Issue by daflockinger** [daflockinger/groschn#10]
[35mgroschn-blockchain-3_1  |[0m Exception in thread "pool-1-thread-33" java.lang.ArrayIndexOutOfBoundsException: 80
[35mgroschn-blockchain-3_1  |[0m 	at org.bouncycastle.crypto.digests.LongDigest.processWord(Unknown Source)
[35mgroschn-blockchain-3_1  |[0m 	at org.bouncycastle.crypto.digests.LongDigest.update(Unknown Source)
[35mgroschn-blockchain-3_1  |[0m 	at org.bouncycastle.jcajce.provider.digest.BCMessageDigest.engineUpdate(Unknown Source)
[35mgroschn-blockchain-3_1  |[0m 	at java.base/java.security.MessageDigest.update(MessageDigest.java:355)
[35mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.commons.hash.MultiHashGenerator.hashWithDigest(MultiHashGenerator.java:68)
[35mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.commons.hash.MultiHashGenerator.doubleHash(MultiHashGenerator.java:57)
[35mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.commons.hash.MultiHashGenerator.generateHash(MultiHashGenerator.java:53)
[35mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.commons.hash.MultiHashGenerator.isHashCorrect(MultiHashGenerator.java:74)
[35mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.validation.impl.BlockValidator.verifyLastHash(BlockValidator.java:91)
[35mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.validation.impl.BlockValidator.validate(BlockValidator.java:52)
[35mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.impl.BlockStorageServiceImpl.validateBlock(BlockStorageServiceImpl.java:51)
[35mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.impl.BlockStorageServiceImpl.saveInBlockchain(BlockStorageServiceImpl.java:43)
[35mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.impl.FreshBlockListener.handleMessage(FreshBlockListener.java:36)
[35mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.impl.FreshBlockListener.handleMessage(FreshBlockListener.java:19)
[35mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.messaging.inbound.AbstractMessageListener.receiveMessage(AbstractMessageListener.java:35)
[35mgroschn-blockchain-3_1  |[0m 	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept(DefaultClusterCommunicationService.java:262)
[35mgroschn-blockchain-3_1  |[0m 	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept(DefaultClusterCommunicationService.java:251)
[35mgroschn-blockchain-3_1  |[0m 	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$null$18(NettyMessagingService.java:520)
[35mgroschn-blockchain-3_1  |[0m 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[35mgroschn-blockchain-3_1  |[0m 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[35mgroschn-blockchain-3_1  |[0m 	at java.base/java.lang.Thread.run(Thread.java:844)

[32mgroschn-blockchain-3_1  |[0m Exception in thread "pool-1-thread-6" java.lang.ArrayIndexOutOfBoundsException: 80
[32mgroschn-blockchain-3_1  |[0m 	at org.bouncycastle.crypto.digests.LongDigest.processWord(Unknown Source)
[32mgroschn-blockchain-3_1  |[0m 	at org.bouncycastle.crypto.digests.LongDigest.update(Unknown Source)
[32mgroschn-blockchain-3_1  |[0m 	at org.bouncycastle.jcajce.provider.digest.BCMessageDigest.engineUpdate(Unknown Source)
[32mgroschn-blockchain-3_1  |[0m 	at java.base/java.security.MessageDigest.update(MessageDigest.java:355)
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.commons.hash.MultiHashGenerator.hashWithDigest(MultiHashGenerator.java:68)
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.commons.hash.MultiHashGenerator.doubleHash(MultiHashGenerator.java:57)
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.commons.hash.MultiHashGenerator.generateHash(MultiHashGenerator.java:53)
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.commons.hash.MultiHashGenerator.isHashCorrect(MultiHashGenerator.java:74)
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.validation.impl.BlockValidator.verifyLastHash(BlockValidator.java:91)
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.validation.impl.BlockValidator.validate(BlockValidator.java:52)
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.impl.BlockStorageServiceImpl.validateBlock(BlockStorageServiceImpl.java:51)
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.impl.BlockStorageServiceImpl.saveInBlockchain(BlockStorageServiceImpl.java:43)
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.impl.FreshBlockListener.handleMessage(FreshBlockListener.java:36)
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.impl.FreshBlockListener.handleMessage(FreshBlockListener.java:19)
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.messaging.inbound.AbstractMessageListener.receiveMessage(AbstractMessageListener.java:35)
[32mgroschn-blockchain-3_1  |[0m 	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept(DefaultClusterCommunicationService.java:262)
[32mgroschn-blockchain-3_1  |[0m 	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept(DefaultClusterCommunicationService.java:251)
[32mgroschn-blockchain-3_1  |[0m 	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$null$18(NettyMessagingService.java:520)
[32mgroschn-blockchain-3_1  |[0m 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[32mgroschn-blockchain-3_1  |[0m 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[32mgroschn-blockchain-3_1  |[0m 	at java.base/java.lang.Thread.run(Thread.java:844)

[32mgroschn-blockchain-3_1  |[0m java.lang.ArrayIndexOutOfBoundsException: 8
[32mgroschn-blockchain-3_1  |[0m 	at org.bouncycastle.crypto.digests.LongDigest.update(Unknown Source) ~[bcprov-jdk15on-1.59.jar!/:1.59.0]
[32mgroschn-blockchain-3_1  |[0m 	at org.bouncycastle.crypto.digests.LongDigest.update(Unknown Source) ~[bcprov-jdk15on-1.59.jar!/:1.59.0]
[32mgroschn-blockchain-3_1  |[0m 	at org.bouncycastle.jcajce.provider.digest.BCMessageDigest.engineUpdate(Unknown Source) ~[bcprov-jdk15on-1.59.jar!/:1.59.0]
[32mgroschn-blockchain-3_1  |[0m 	at java.base/java.security.MessageDigest.update(MessageDigest.java:355) ~[na:na]
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.commons.hash.MultiHashGenerator.hashWithDigest(MultiHashGenerator.java:68) ~[commons-0.0.1.jar!/:0.0.1]
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.commons.hash.MultiHashGenerator.doubleHash(MultiHashGenerator.java:57) ~[commons-0.0.1.jar!/:0.0.1]
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.commons.hash.MultiHashGenerator.generateHash(MultiHashGenerator.java:53) ~[commons-0.0.1.jar!/:0.0.1]
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.consensus.impl.ProofOfWorkAlgorithm.forgeBlock(ProofOfWorkAlgorithm.java:103) ~[classes!/:0.0.1]
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.consensus.impl.ProofOfWorkAlgorithm.reachConsensus(ProofOfWorkAlgorithm.java:71) ~[classes!/:0.0.1]
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.consensus.impl.ConsensusFactory.reachConsensus(ConsensusFactory.java:55) ~[classes!/:0.0.1]
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.impl.BlockMakerImpl.forgeBlockUnsafe(BlockMakerImpl.java:72) ~[classes!/:0.0.1]
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.impl.BlockMakerImpl.produceBlock(BlockMakerImpl.java:65) ~[classes!/:0.0.1]
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.PunchTimer.restartOnTimeout(PunchTimer.java:52) ~[classes!/:0.0.1]
[32mgroschn-blockchain-3_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.PunchTimer.checkMiningProcess(PunchTimer.java:38) ~[classes!/:0.0.1]
[32mgroschn-blockchain-3_1  |[0m 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
[32mgroschn-blockchain-3_1  |[0m 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
[32mgroschn-blockchain-3_1  |[0m 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
[32mgroschn-blockchain-3_1  |[0m 	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
[32mgroschn-blockchain-3_1  |[0m 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
[32mgroschn-blockchain-3_1  |[0m 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.10.RELEASE.jar!/:5.0.10.RELEASE]
[32mgroschn-blockchain-3_1  |[0m 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [na:na]
[32mgroschn-blockchain-3_1  |[0m 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [na:na]
[32mgroschn-blockchain-3_1  |[0m 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [na:na]
[32mgroschn-blockchain-3_1  |[0m 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [na:na]
[32mgroschn-blockchain-3_1  |[0m 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [na:na]
[32mgroschn-blockchain-3_1  |[0m 	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]

[32mgroschn-blockchain-3_1  |[0m 2018-11-03 09:52:25.728  INFO 1 --- [ool-1-thread-37] c.f.g.b.m.sync.impl.BlockSynchronizer    : got related infos
[32mgroschn-blockchain-3_1  |[0m 2018-11-03 09:52:25.728  INFO 1 --- [ool-1-thread-37] c.f.g.b.m.sync.impl.BlockSynchronizer    : fetching next block batch
[32mgroschn-blockchain-3_1  |[0m 2018-11-03 09:52:25.733  INFO 1 --- [ool-1-thread-37] c.f.g.b.m.sync.impl.BlockSynchronizer    : Synchronization finished
[32mgroschn-blockchain-3_1  |[0m 2018-11-03 09:52:38.693 ERROR 1 --- [pool-3-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
[32mgroschn-blockchain-3_1  |[0m 
[32mgroschn-blockchain-3_1  |[0m java.lang.ArrayIndexOutOfBoundsException: null
[32mgroschn-blockchain-3_1  |[0m 
[32mgroschn-blockchain-3_1  |[0m 2018-11-03 09:52:38.695  INFO 1 --- [ool-1-thread-27] c.f.g.b.m.s.impl.BlockSyncDeterminator   : Sync point found at position: 6
[32mgroschn-blockchain-3_1  |[0m 2018-11-03 09:52:38.696  INFO 1 --- [ool-1-thread-27] c.f.g.b.m.s.impl.BlockSyncDeterminator   : Successfully removed wrong blocks.

[31mgroschn-blockchain-2_1  |[0m 2018-11-03 09:53:43.088 ERROR 1 --- [pool-3-thread-1] c.f.g.blockchain.blockworks.BlockMaker   : Something went wrong while creating a new Block

[31mgroschn-blockchain-2_1  |[0m 2018-11-03 09:40:50.831  INFO 1 --- [ool-1-thread-16] c.f.g.b.m.sync.impl.BlockSynchronizer    : fetching next block batch
[31mgroschn-blockchain-2_1  |[0m 2018-11-03 09:40:50.831 ERROR 1 --- [pool-3-thread-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.
[31mgroschn-blockchain-2_1  |[0m 
[31mgroschn-blockchain-2_1  |[0m java.lang.ArrayIndexOutOfBoundsException: null
[31mgroschn-blockchain-2_1  |[0m 
[31mgroschn-blockchain-2_1  |[0m 2018-11-03 09:40:50.849  INFO 1 --- [ool-1-thread-16] c.f.g.b.m.sync.impl.BlockSynchronizer    : done fetching next block batch
[31mgroschn-blockchain-2_1  |[0m 2018-11-03 09:40:50.850  INFO 1 --- [ool-1-thread-16] c.f.g.b.m.sync.impl.BlockSynchronizer    : Did response validate correct: false

[35mgroschn-blockchain-1_1  |[0m java.lang.IllegalStateException: attempt to absorb with odd length queue
[35mgroschn-blockchain-1_1  |[0m 	at org.bouncycastle.crypto.digests.KeccakDigest.absorb(Unknown Source) ~[bcprov-jdk15on-1.59.jar!/:1.59.0]
[35mgroschn-blockchain-1_1  |[0m 	at org.bouncycastle.crypto.digests.KeccakDigest.update(Unknown Source) ~[bcprov-jdk15on-1.59.jar!/:1.59.0]
[35mgroschn-blockchain-1_1  |[0m 	at org.bouncycastle.jcajce.provider.digest.BCMessageDigest.engineUpdate(Unknown Source) ~[bcprov-jdk15on-1.59.jar!/:1.59.0]
[35mgroschn-blockchain-1_1  |[0m 	at java.base/java.security.MessageDigest.update(MessageDigest.java:355) ~[na:na]
[35mgroschn-blockchain-1_1  |[0m 	at com.flockinger.groschn.commons.hash.MultiHashGenerator.hashWithDigest(MultiHashGenerator.java:68) ~[commons-0.0.1.jar!/:0.0.1]
[35mgroschn-blockchain-1_1  |[0m 	at com.flockinger.groschn.commons.hash.MultiHashGenerator.doubleHash(MultiHashGenerator.java:58) ~[commons-0.0.1.jar!/:0.0.1]
[35mgroschn-blockchain-1_1  |[0m 	at com.flockinger.groschn.commons.hash.MultiHashGenerator.generateHash(MultiHashGenerator.java:53) ~[commons-0.0.1.jar!/:0.0.1]
[35mgroschn-blockchain-1_1  |[0m 	at com.flockinger.groschn.commons.hash.MultiHashGenerator.isHashCorrect(MultiHashGenerator.java:74) ~[commons-0.0.1.jar!/:0.0.1]
[35mgroschn-blockchain-1_1  |[0m 	at com.flockinger.groschn.blockchain.validation.impl.BlockValidator.verifyLastHash(BlockValidator.java:91) ~[classes!/:0.0.1]
[35mgroschn-blockchain-1_1  |[0m 	at com.flockinger.groschn.blockchain.validation.impl.BlockValidator.validate(BlockValidator.java:52) ~[classes!/:0.0.1]
[35mgroschn-blockchain-1_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.impl.BlockStorageServiceImpl.validateBlock(BlockStorageServiceImpl.java:51) ~[classes!/:0.0.1]
[35mgroschn-blockchain-1_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.impl.BlockStorageServiceImpl.saveInBlockchain(BlockStorageServiceImpl.java:43) ~[classes!/:0.0.1]
[35mgroschn-blockchain-1_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.impl.FreshBlockListener.handleMessage(FreshBlockListener.java:36) [classes!/:0.0.1]
[35mgroschn-blockchain-1_1  |[0m 	at com.flockinger.groschn.blockchain.blockworks.impl.FreshBlockListener.handleMessage(FreshBlockListener.java:19) [classes!/:0.0.1]
[35mgroschn-blockchain-1_1  |[0m 	at com.flockinger.groschn.messaging.inbound.AbstractMessageListener.receiveMessage(AbstractMessageListener.java:35) [messaging-0.0.1.jar!/:0.0.1]
[35mgroschn-blockchain-1_1  |[0m 	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept(DefaultClusterCommunicationService.java:262) ~[atomix-cluster-3.0.0-rc11.jar!/:na]
[35mgroschn-blockchain-1_1  |[0m 	at io.atomix.cluster.messaging.impl.DefaultClusterCommunicationService$InternalMessageConsumer.accept(DefaultClusterCommunicationService.java:251) ~[atomix-cluster-3.0.0-rc11.jar!/:na]
[35mgroschn-blockchain-1_1  |[0m 	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$null$18(NettyMessagingService.java:520) ~[atomix-cluster-3.0.0-rc11.jar!/:na]
[35mgroschn-blockchain-1_1  |[0m 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:na]
[35mgroschn-blockchain-1_1  |[0m 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
[35mgroschn-blockchain-1_1  |[0m 	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]

**Comment by daflockinger** [comment]
tested, fixed.
